export const FETCH_INIT = "FETCH_INIT";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_DIFFICULTY = "SELECT_DIFFICULTY";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const TRIVIA_COMPLETE = "TRIVIA_COMPLETE";
export const TRIVIA_INIT = "TRIVIA_INIT";
